import type {Locale} from "./messages";
const fr={
 contacts:"Contacts",services:"Prestations",opportunities:"Opportunités",tasks:"Tâches",create:"Créer",edit:"Modifier",save:"Enregistrer",remove:"Supprimer",confirm:"Confirmer la suppression",confirmDetail:"Cette suppression est définitive. Les éléments liés empêchent la suppression.",close:"Fermer",search:"Rechercher",apply:"Rechercher",next:"Page suivante",reset:"Revenir au début",empty:"Aucun élément enregistré",loading:"Chargement des données…",error:"Les données n’ont pas pu être chargées.",retry:"Réessayer",invalid:"Vérifiez les champs du formulaire.",conflict:"Conflit : relisez les données. Une version plus récente, un doublon ou une référence liée empêche cette action.",uncertain:"Résultat incertain. Relisez la liste avant de confirmer une nouvelle création. Aucun renvoi automatique n’est effectué.",saved:"Modification enregistrée.",readOnly:"Lecture seule",details:"Voir la fiche",name:"Nom",phone:"Téléphone international",email:"Email (facultatif)",title:"Intitulé",description:"Description (facultative)",currency:"Devise",averageAmountMinor:"Valeur moyenne indicative (unités mineures)",minAmountMinor:"Valeur minimale indicative (unités mineures)",maxAmountMinor:"Valeur maximale indicative (unités mineures)",durationMinutes:"Durée indicative (minutes)",active:"Prestation active",contactId:"Contact",serviceTemplateId:"Prestation (facultative)",opportunityId:"Opportunité",dueAt:"Échéance UTC (facultative)",dueHelp:"Format ISO, par exemple 2026-10-04T10:00:00Z. Affichage selon la timezone de votre organisation dans Aujourd’hui.",status:"État",none:"Aucune",choose:"Choisir",overdue:"En retard",due:"À faire aujourd’hui",toProcess:"Opportunités à traiter",dayZone:"Journée de l’organisation",filter:"Filtrer par état",all:"Tous",new:"Nouveau",toContact:"À contacter",waiting:"En attente du client",won:"Gagné",lost:"Perdu",archived:"Archivé",open:"À faire",done:"Terminée",priceNote:"Prix indicatifs uniquement : aucun devis, chiffre d’affaires ou conversion de devise.",limited:"Liste limitée à 25 éléments par groupe. Consultez les listes pour la suite.",
};
export type CrmMessages={ [K in keyof typeof fr]:string};
const en:CrmMessages={
 contacts:"Contacts",services:"Services",opportunities:"Opportunities",tasks:"Tasks",create:"Create",edit:"Edit",save:"Save",remove:"Delete",confirm:"Confirm deletion",confirmDetail:"Deletion is permanent. Linked records prevent deletion.",close:"Close",search:"Search",apply:"Search",next:"Next page",reset:"Back to start",empty:"No saved records",loading:"Loading records…",error:"Records could not load.",retry:"Try again",invalid:"Check the form fields.",conflict:"Conflict: reload records. A newer version, duplicate or linked record prevents this action.",uncertain:"Uncertain outcome. Read the list before confirming another creation. Nothing is resent automatically.",saved:"Change saved.",readOnly:"Read only",details:"View record",name:"Name",phone:"International phone",email:"Email (optional)",title:"Title",description:"Description (optional)",currency:"Currency",averageAmountMinor:"Indicative average (minor units)",minAmountMinor:"Indicative minimum (minor units)",maxAmountMinor:"Indicative maximum (minor units)",durationMinutes:"Indicative duration (minutes)",active:"Active service",contactId:"Contact",serviceTemplateId:"Service (optional)",opportunityId:"Opportunity",dueAt:"UTC deadline (optional)",dueHelp:"ISO format, for example 2026-10-04T10:00:00Z. Today uses your organization's timezone.",status:"Status",none:"None",choose:"Choose",overdue:"Overdue",due:"Due today",toProcess:"Opportunities to process",dayZone:"Organization day",filter:"Filter by status",all:"All",new:"New",toContact:"To contact",waiting:"Waiting for customer",won:"Won",lost:"Lost",archived:"Archived",open:"Open",done:"Done",priceNote:"Indicative prices only: no quote, revenue or currency conversion.",limited:"Each group is limited to 25 records. Use the lists to see more.",
};
export const crmDictionaries:Record<Locale,CrmMessages>={"fr-FR":fr,"en-GB":en};
export function statusLabel(status:string,t:CrmMessages){return ({NEW:t.new,TO_CONTACT:t.toContact,WAITING_CUSTOMER:t.waiting,WON:t.won,LOST:t.lost,ARCHIVED:t.archived,OPEN:t.open,DONE:t.done} as Record<string,string>)[status]??status;}
