import type { Locale } from "./messages";
export const shellFr = {
 navigation: "Navigation principale", menu: "Ouvrir le menu", close: "Fermer", workspace: "Votre espace", development: "Version de développement", signout: "Se déconnecter", refresh: "Réessayer",
 today: "Aujourd’hui", opportunities: "Opportunités", contacts: "Contacts", services: "Prestations", settings: "Paramètres",
 todayIntro: "L’essentiel pour avancer, au même endroit.", opportunitiesIntro: "Vos demandes et leur prochaine étape.", contactsIntro: "Les personnes avec qui vous travaillez.", servicesIntro: "Les prestations que vous proposez.", settingsIntro: "Un espace adapté à votre entreprise.",
 todayEmpty: "Votre journée commence ici", opportunitiesEmpty: "Vos prochaines opportunités apparaîtront ici", contactsEmpty: "Votre carnet de contacts prend forme", servicesEmpty: "Votre catalogue se prépare", settingsEmpty: "Vos paramètres arrivent bientôt",
 todayDetail: "Les demandes à traiter et les prochaines actions seront réunies ici lorsque ces fonctions seront disponibles.", opportunitiesDetail: "Le suivi des demandes sera ajouté à une prochaine étape. Aucune opportunité réelle n’est collectée pour le moment.", contactsDetail: "La gestion des contacts sera disponible à une prochaine étape. Aucun contact réel n’est enregistré ici.", servicesDetail: "Vous pourrez définir vos prestations dans une prochaine version. Aucun prix ni service n’est inventé.", settingsDetail: "La modification des paramètres n’est pas encore disponible. Aucune donnée métier ne peut être enregistrée depuis cet écran.",
 next: "Une expérience pensée pour le terrain", nextDetail: "Un espace simple pour retrouver vos demandes et savoir quoi faire ensuite.", learn: "À propos de cet espace", aboutTitle: "Les écrans se construisent", aboutDetail: "Cette version présente la navigation et les composants. Les fonctions métier seront ajoutées progressivement après validation.",
 loading: "Vérification de votre accès…", required: "Une connexion est nécessaire", requiredDetail: "Connectez-vous avec une session autorisée pour accéder à votre espace. Aucune donnée d’organisation n’est affichée ici.", denied: "Cet espace n’est pas disponible", deniedDetail: "Vérifiez votre accès auprès du propriétaire de votre organisation.", error: "L’espace n’a pas pu être chargé", errorDetail: "Réessayez dans un instant. Aucune donnée d’organisation n’est affichée pendant cette interruption.", home: "Retour à l’accueil", local: "Développement local · Aucune donnée réelle", checking: "Chargement", demoTitle: "Exemple de formulaire", demoDetail: "Démonstration d’interface uniquement. Les informations saisies ne sont ni envoyées ni enregistrées.", demoOpen: "Voir un exemple de formulaire", label: "Intitulé de démonstration", placeholder: "Un intitulé fictif", demoValidate: "Vérifier l’exemple", demoInvalid: "Saisissez un intitulé de 2 à 40 caractères.", demoValid: "Exemple valide. Aucune donnée n’a été enregistrée.",
} as const;
export type ShellMessages = { [K in keyof typeof shellFr]: string };
const shellEn: ShellMessages = {
 navigation: "Main navigation", menu: "Open menu", close: "Close", workspace: "Your workspace", development: "Development version", signout: "Sign out", refresh: "Try again",
 today: "Today", opportunities: "Opportunities", contacts: "Contacts", services: "Services", settings: "Settings",
 todayIntro: "Everything you need to move forward, in one place.", opportunitiesIntro: "Your enquiries and their next steps.", contactsIntro: "The people you work with.", servicesIntro: "The services you offer.", settingsIntro: "A workspace that fits your business.",
 todayEmpty: "Your day starts here", opportunitiesEmpty: "Your next opportunities will appear here", contactsEmpty: "Your contact book is taking shape", servicesEmpty: "Your catalogue is on its way", settingsEmpty: "Your settings are coming soon",
 todayDetail: "Enquiries and next actions will appear here when these features become available.", opportunitiesDetail: "Enquiry tracking will come in a later step. No real opportunity is collected yet.", contactsDetail: "Contact management will come in a later step. No real contact is stored here.", servicesDetail: "You will define your services in a later version. No prices or services are made up.", settingsDetail: "Changing settings is not available yet. This screen cannot save business data.",
 next: "Designed for field work", nextDetail: "A simple workspace to find your enquiries and know what to do next.", learn: "About this workspace", aboutTitle: "The screens are taking shape", aboutDetail: "This version presents navigation and components. Business features will be added gradually after review.",
 loading: "Checking your access…", required: "Please sign in", requiredDetail: "Use an authorized session to access your workspace. No organization data is shown here.", denied: "This workspace is unavailable", deniedDetail: "Check your access with your organization's owner.", error: "The workspace could not load", errorDetail: "Try again shortly. No organization data is shown during this interruption.", home: "Back to home", local: "Local development · No real data", checking: "Loading", demoTitle: "Form example", demoDetail: "Interface demonstration only. What you enter is never sent or saved.", demoOpen: "View a form example", label: "Example title", placeholder: "A fictional title", demoValidate: "Check the example", demoInvalid: "Enter a title between 2 and 40 characters.", demoValid: "Valid example. Nothing has been saved.",
};
export const shellDictionaries: Record<Locale, ShellMessages> = { "fr-FR": shellFr, "en-GB": shellEn };
