"use client";
import {useCallback,useEffect,useRef,useState,useId,type FormEvent} from "react";
import {z} from "zod";
import {Button,Card,Alert,Field,Skeleton} from "@/shared/ui/primitives";
import {Dialog} from "@/shared/ui/dialog";
import {crmDictionaries,statusLabel,type CrmMessages} from "@/shared/i18n/crm";
import {defaultLocale} from "@/shared/i18n/messages";
import {inputs,updates,validateAmounts,opportunityStates,type Kind} from "./validation";
import {parseAmount,amountInput} from "./money-input";
import {formatMoney} from "@/shared/i18n/format";
import {rows} from "./dto";
type Item={id:string;version:number;[key:string]:unknown};
type Listing={items:Item[];nextCursor:string|null;canWrite:boolean};
const title=(row:Item)=>String(row.name??row.title);
async function checked(response:Response){const data:unknown=await response.json();if(!response.ok)throw Object.assign(new Error("Request refused"),{status:response.status});return data;}
function Picker({org,kind,name,label,value,t,error,prefix}:{prefix:string;org:string;kind:Kind;name:string;label:string;value:string;t:CrmMessages;error:boolean}) {
 const fieldId=`${prefix}-${name}`;
 const [selected,setSelected]=useState(value),[selectedLabel,setSelectedLabel]=useState(value);
 const [options,setOptions]=useState<Item[]>([]),[q,setQ]=useState(""),[cursor,setCursor]=useState<string|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{const c=new AbortController();void fetch(`/api/crm/${org}/${kind}?limit=50`,{cache:"no-store",signal:c.signal}).then(checked).then(data=>{if(!c.signal.aborted){const d=z.object({items:z.array(rows[kind]),nextCursor:z.uuid().nullable(),canWrite:z.boolean()}).strict().parse(data);setOptions(d.items);setCursor(d.nextCursor);}}).catch(()=>{if(!c.signal.aborted)setFailed(true);});return()=>c.abort();},[org,kind]);
 async function search(next=false){setFailed(false);try{const data=await checked(await fetch(`/api/crm/${org}/${kind}?limit=50&q=${encodeURIComponent(q)}${next&&cursor?`&cursor=${cursor}`:""}`,{cache:"no-store"}));const d=z.object({items:z.array(rows[kind]),nextCursor:z.uuid().nullable(),canWrite:z.boolean()}).strict().parse(data);setOptions(d.items);setCursor(d.nextCursor);}catch{setFailed(true);}}
 return <div className="ui-field"><label htmlFor={fieldId}>{label}</label><select id={fieldId} name={name} value={selected} onChange={e=>{setSelected(e.target.value);setSelectedLabel(e.target.selectedOptions[0]?.textContent??t.choose);}} aria-invalid={error} aria-describedby={error?`${prefix}-error`:undefined} required={name!=="serviceTemplateId"}><option value="">{name==="serviceTemplateId"?t.none:t.choose}</option>{selected&&!options.some(r=>r.id===selected)&&<option value={selected}>{selectedLabel}</option>}{options.map(row=><option key={row.id} value={row.id}>{title(row)}</option>)}</select><Field id={`${fieldId}-search`} label={`${t.search} — ${label}`} value={q} maxLength={120} onChange={e=>setQ(e.target.value)}/><div className="state-actions"><Button variant="quiet" onClick={()=>void search()}>{t.apply}</Button>{cursor&&<Button variant="quiet" onClick={()=>void search(true)}>{t.next}</Button>}</div>{failed&&<Alert error>{t.error}</Alert>}</div>;
}
const fields:Record<Kind,string[]>={contacts:["name","phone","email"],services:["name","description","currency","averageAmountMinor","minAmountMinor","maxAmountMinor","durationMinutes","active"],opportunities:["title","description","contactId","serviceTemplateId"],tasks:["title","opportunityId","dueAt"]};
function Editor({org,kind,row,save,t}:{org:string;kind:Kind;row?:Item;save:(data:Record<string,unknown>,method:"POST"|"PATCH",id?:string)=>Promise<void>;t:CrmMessages}) {
 const prefix=useId(),[currency,setCurrency]=useState(String(row?.currency??"EUR"));
 const [error,setError]=useState(""),[pending,setPending]=useState(false);const busy=useRef(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy.current)return;const form=e.currentTarget;const fd=new FormData(form),data:Record<string,unknown>={};
  for(const key of fields[kind]){const v=fd.get(key);data[key]=["averageAmountMinor","minAmountMinor","maxAmountMinor"].includes(key)?parseAmount(String(v??""),currency):key==="durationMinutes"?v===""?null:Number(v):key==="active"?v==="on":typeof v==="string"&&v.trim()!==""?v.trim():["name","title","phone","currency","contactId","opportunityId"].includes(key)?"":null;}
  if(row){data.version=row.version;if(kind==="opportunities"||kind==="tasks")data.status=fd.get("status");}
  const parsed=(row?updates[kind]:inputs[kind]).safeParse(data);if(!parsed.success||kind==="services"&&!validateAmounts(data)){setError(t.invalid);form.querySelector<HTMLElement>('input,select')?.focus();return;}
  busy.current=true;setPending(true);setError("");try{await save(data,row?"PATCH":"POST",row?.id);form.closest("dialog")?.close();form.reset();}catch(e){const status=(e as {status?:number}).status;setError(status===409?t.conflict:status===400?t.invalid:t.uncertain);}finally{busy.current=false;setPending(false);}
 }
 return <form className="crm-form" onSubmit={e=>void submit(e)} noValidate>{error&&<p id={`${prefix}-error`} role="alert" className="ui-alert ui-alert--error">{error}</p>}{fields[kind].map(key=> {
  const label=t[key as keyof CrmMessages];if(key.endsWith("Id"))return <Picker key={key} prefix={prefix} org={org} kind={key==="contactId"?"contacts":key==="serviceTemplateId"?"services":"opportunities"} name={key} label={label} value={String(row?.[key]??"")} t={t} error={Boolean(error)}/>;
  if(key==="active")return <label key={key} className="crm-check"><input type="checkbox" name={key} defaultChecked={row?Boolean(row.active):true}/>{label}</label>;
  if(key==="currency")return <div key={key} className="ui-field"><label htmlFor={`${prefix}-${key}`}>{label}</label><select id={`${prefix}-${key}`} name={key} value={currency} onChange={e=>setCurrency(e.target.value)}>{["EUR","GBP","USD","JPY","KWD"].map(c=><option key={c}>{c}</option>)}</select></div>;
  return <Field key={key} id={`${prefix}-${key}`} name={key} label={label} defaultValue={["averageAmountMinor","minAmountMinor","maxAmountMinor"].includes(key)?amountInput(row?.[key],currency):String(row?.[key]??"")} inputMode={key.endsWith("AmountMinor")?"decimal":undefined} type={key==="email"?"email":key==="durationMinutes"?"number":"text"} maxLength={key==="description"?2000:key==="name"?120:key==="title"?160:key==="email"?254:80} error={error? t.invalid:undefined}/>;
 })}{kind==="tasks"&&<p>{t.dueHelp}</p>}{row&&(kind==="opportunities"||kind==="tasks")&&<div className="ui-field"><label htmlFor={`${prefix}-status`}>{t.status}</label><select id={`${prefix}-status`} name="status" defaultValue={String(row.status)}>{(kind==="tasks"?["OPEN","DONE"]:opportunityStates).map(s=><option key={s} value={s}>{statusLabel(s,t)}</option>)}</select></div>}{kind==="services"&&<p>{t.priceNote}</p>}<Button type="submit" disabled={pending}>{t.save}</Button></form>;
}
export function CrmPanel({organizationId:org,kind,onDenied,onChanged}:{organizationId:string;kind:Kind;onDenied:()=>void;onChanged?:()=>void}) {
 const t=crmDictionaries[defaultLocale],[data,setData]=useState<Listing|null>(null),[error,setError]=useState(false),[q,setQ]=useState(""),[status,setStatus]=useState(""),[cursor,setCursor]=useState<string|null>(null),[notice,setNotice]=useState("");const controller=useRef<AbortController|null>(null),alive=useRef(true),heading=useRef<HTMLHeadingElement>(null);
 const load=useCallback(async()=>{controller.current?.abort();const c=new AbortController();controller.current=c;try{const response=await fetch(`/api/crm/${org}/${kind}?q=${encodeURIComponent(q)}${status?`&status=${status}`:""}${cursor?`&cursor=${cursor}`:""}`,{cache:"no-store",signal:c.signal});const d=z.object({items:z.array(rows[kind]),nextCursor:z.uuid().nullable(),canWrite:z.boolean()}).strict().parse(await checked(response));if(!c.signal.aborted&&alive.current){setError(false);setData(d);}}catch(e){if(c.signal.aborted||!alive.current)return;if([401,404].includes((e as {status:number}).status)){onDenied();return;}setError(true);}},[org,kind,q,status,cursor,onDenied]);
 useEffect(()=>{alive.current=true;const timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);alive.current=false;controller.current?.abort();};},[load]);
 async function save(input:Record<string,unknown>,method:"POST"|"PATCH"|"DELETE",id?:string){const c=controller.current;const response=await fetch(`/api/crm/${org}/${kind}${id?`/${id}`:""}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(input),cache:"no-store",...(c?{signal:c.signal}:{})});if([401,404].includes(response.status)){onDenied();}await checked(response);if(!alive.current)return;setNotice(t.saved);onChanged?.();setTimeout(()=>{if(alive.current)void load();},0);}
 return <Card className="crm-panel"><h2 ref={heading} tabIndex={-1}>{t[kind]}</h2>{notice&&<Alert>{notice}</Alert>}{data?.canWrite?<Dialog lazy label={`${t.create} — ${t[kind]}`} title={`${t.create} — ${t[kind]}`} close={t.close}><Editor org={org} kind={kind} save={save} t={t}/></Dialog>:data&&<p>{t.readOnly}</p>}
 <div className="state-actions"><Button variant="secondary" onClick={()=>{setError(false);setData(null);void load();}}>{t.retry}</Button></div>
 <div className="crm-filters"><Field id={`search-${kind}`} label={t.search} value={q} onChange={e=>{setData(null);setError(false);setCursor(null);setQ(e.target.value);}} maxLength={120}/>{["tasks","opportunities"].includes(kind)&&<div className="ui-field"><label htmlFor={`filter-${kind}`}>{t.filter}</label><select id={`filter-${kind}`} value={status} onChange={e=>{setData(null);setError(false);setCursor(null);setStatus(e.target.value);}}><option value="">{t.all}</option>{(kind==="tasks"?["OPEN","DONE"]:opportunityStates).map(s=><option key={s} value={s}>{statusLabel(s,t)}</option>)}</select></div>}</div>
 {error?<Alert error>{t.error}<Button onClick={()=>void load()}>{t.retry}</Button></Alert>:!data?<Skeleton label={t.loading}/>:data.items.length===0?<p>{t.empty}</p>:<ul className="crm-list">{data.items.map(row=><li key={row.id}><h3>{title(row)}</h3>{typeof row.status==="string"&&<p>{statusLabel(row.status,t)}</p>}<details><summary>{t.details}</summary><dl>{fields[kind].filter(k=>!k.endsWith("Id")).map(k=><div key={k}><dt>{t[k as keyof CrmMessages]}</dt><dd>{row[k]===null?t.none:typeof row[k]==="boolean"?row[k]?t.yes:t.no:k.endsWith("AmountMinor")?formatMoney(Number(row[k]),String(row.currency),defaultLocale):String(row[k])}</dd></div>)}</dl></details>{data.canWrite&&<div className="state-actions"><Dialog lazy label={t.edit} title={`${t.edit} — ${title(row)}`} close={t.close}><Editor org={org} kind={kind} row={row} save={save} t={t}/></Dialog><Delete org={org} row={row} save={save} t={t} after={()=>heading.current?.focus()}/></div>}</li>)}</ul>}
 <div className="state-actions">{cursor&&<Button onClick={()=>{setData(null);setError(false);setCursor(null);}}>{t.reset}</Button>}{data?.nextCursor&&<Button onClick={()=>{setData(null);setError(false);setCursor(data.nextCursor);}}>{t.next}</Button>}</div></Card>;
}
function Delete({row,save,t,after}:{org:string;row:Item;save:(data:Record<string,unknown>,method:"DELETE",id:string)=>Promise<void>;t:CrmMessages;after:()=>void}) {
 const [error,setError]=useState(false),[pending,setPending]=useState(false);const busy=useRef(false);
 return <Dialog lazy label={t.remove} title={`${t.confirm} — ${title(row)}`} close={t.close}><p>{t.confirmDetail}</p>{error&&<Alert error>{t.conflict}</Alert>}<Button disabled={pending} onClick={async e=>{if(busy.current)return;busy.current=true;setPending(true);const dialog=e.currentTarget.closest("dialog");try{await save({version:row.version},"DELETE",row.id);dialog?.close();after();}catch{setError(true);}finally{busy.current=false;setPending(false);}}}>{t.confirm}</Button></Dialog>;
}
const todayDto=z.object({overdue:z.array(z.object({id:z.uuid(),title:z.string(),dueAt:z.iso.datetime().nullable(),status:z.string(),version:z.number(),opportunityId:z.uuid()}).strict()),due:z.array(z.object({id:z.uuid(),title:z.string(),dueAt:z.iso.datetime().nullable(),status:z.string(),version:z.number(),opportunityId:z.uuid()}).strict()),opportunities:z.array(z.object({id:z.uuid(),title:z.string(),status:z.string(),version:z.number()}).strict()),timeZone:z.string(),start:z.iso.datetime(),finish:z.iso.datetime(),canWrite:z.boolean()}).strict();
export function Today({org,onDenied}:{org:string;onDenied:()=>void}) {
 const t=crmDictionaries[defaultLocale],[data,setData]=useState<z.infer<typeof todayDto>|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 const changed=useCallback(()=>{setData(null);setError(false);setRetry(v=>v+1);},[]);
 useEffect(()=>{const c=new AbortController();void fetch(`/api/crm/${org}/today`,{cache:"no-store",signal:c.signal}).then(checked).then(d=>{if(!c.signal.aborted)setData(todayDto.parse(d));}).catch(e=>{if(c.signal.aborted)return;if([401,404].includes(e.status))onDenied();else setError(true);});return()=>c.abort();},[org,onDenied,retry]);
 return <><Card className="crm-panel"><h2>{t.dayZone}</h2>{error?<Alert error>{t.error}<Button onClick={()=>{setError(false);setRetry(v=>v+1);}}>{t.retry}</Button></Alert>:!data?<Skeleton label={t.loading}/>:<><p>{new Intl.DateTimeFormat(defaultLocale,{timeZone:data.timeZone,dateStyle:"long"}).format(new Date(data.start))} · {data.timeZone}</p>{(["overdue","due","opportunities"] as const).map(k=><section key={k}><h3>{t[k==="opportunities"?"toProcess":k]}</h3>{data[k].length===0?<p>{t.empty}</p>:<ul>{data[k].map(r=><li key={r.id}>{r.title}{"dueAt" in r&&r.dueAt&&` · ${new Intl.DateTimeFormat(defaultLocale,{timeZone:data.timeZone,dateStyle:"short",timeStyle:"short"}).format(new Date(r.dueAt))}`}</li>)}</ul>}</section>)}<p>{t.limited}</p></>}</Card><CrmPanel organizationId={org} kind="tasks" onDenied={onDenied} onChanged={changed}/></>;
}
